import { print } from '@swc/core';

/**
 * @param {import('./types.js').Node} node
 */
export const generate = async (node) => {
    if (node.type === 'Program' || node.type === 'Module' || node.type === 'Script') {
        const output = await print(/** @type {import('./types.js').Program} */(node));
        return output.code;
    }

    const expression = /** @type {import('./types.js').Expression} */ (node);

    const { code } = await print(/** @type {import('./types.js').Program} */({
        type: 'Module',
        body: [{
            type: 'ExpressionStatement',
            expression,
            span: {
                start: 0,
                end: 0,
                ctxt: 0,
            },
        }],
        span: {
            start: 0,
            end: 0,
            ctxt: 0,
        },
    }));

    // remove the trailing semicolon generated by the fake expression.
    return code.substring(0, code.length - 2);
};
