name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Install project dependencies
        run: yarn install

      - name: Run typings script
        run: yarn types

      - name: Run build script
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./packages
          retention-days: 1

  test:
    name: Test
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: yarn

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: ./packages

      - name: Install project dependencies
        run: yarn install

      - name: Run tests
        run: yarn test

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: coverage/clover.xml
